import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
] 

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.normal]
family = "MesloLGS NF"

[font.offset]
x = -1
y = -1

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[shell]
program = "tmux"
args = ["new-session", "-A", "-s", "🤓"]

[window]
dynamic_padding = true

[window.padding]
x = 2
y = 2
