import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
] 

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = -1
y = -1

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[shell]
program = "/opt/homebrew/bin/zellij"
args = ["-l", "/Users/oflisback/.config/zellij/layout.kdl", "attach", "--index", "0", "--create"]

[window]
dynamic_padding = true
option_as_alt = "OnlyLeft"
startup_mode = "Fullscreen"

[window.padding]
x = 2
y = 2
