import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
] 

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.offset]
x = -1
y = -1

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

#[[keyboard.bindings]]
#chars = "\u0002\u001B[D"
#key = "H"
#mods = "Alt"

#[[keyboard.bindings]]
#chars = "\u0002\u001B[C"
#key = "L"
#mods = "Alt"

#[[keyboard.bindings]]
#chars = "\u0002\u001B[B"
#key = "J"
#mods = "Alt"

[shell]
program = "/opt/homebrew/bin/zellij"
args = ["-l", "/Users/oflisback/.config/zellij/layout.kdl"]

[window]
dynamic_padding = true
option_as_alt = "OnlyLeft"

[window.padding]
x = 2
y = 2
